excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
function_body_length:
  - 300 # warning
  - 500 # error
line_length:
  warning: 120
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true