# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
# `xcrun simctl list devices available`
devices([
  "iPhone 8 Plus",
  "iPhone SE (3rd generation)",
  "iPhone 13 Pro Max",
  # xcrun simctl create "iPad Pro (12.9-inch) (2nd generation)" "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-"
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (5th generation)"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("ec3730")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
